base_app/account/urls.py
from django.urls import path
from . import views
from rest_framework_jwt.views import obtain_jwt_token

app_name = 'account'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_account, name='login'),
    path('logout/', views.logout_account, name='logout'),
    path('token-auth/', obtain_jwt_token, name='token')
 ]

base_app/base_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# api currency
from currency import api_views as currency_api
from dashboard import api_views as dashboard_api

from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='Pastebin API')

from account.api_views import current_user, UserList


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),

    # page create default tools django
    path('currency/', include('currency.urls', namespace='currency')),
    path('account/', include('account.urls', namespace='account')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

    # api currency
    path('api/currency/redoc', schema_view),
    path('api/currency/', currency_api.currency_list, name='api_currency_list'),
    path('api/currency/<int:pk>', currency_api.currency_detail, name='api_currency_detail'),

    # api dashboard
    path('api/dashboard/', dashboard_api.dashboard_list, name='api_dashboard_list'),
    path('api/dashboard/<int:pk>', dashboard_api.dashboard_detail, name='api_dashboard_detail'),
    
    # api user
    path('api/current_user/', current_user),
    path('api/users/', UserList.as_view())
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base_app/currency/urls.py
from django.urls import path, include
from . import views

app_name = 'currency'

urlpatterns = [
    path('', views.currency_list, name='list'),
]

base_app/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

base_app/home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    path('landing/', views.landing, name='landing'),
 ]

base_app/account/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    picture = models.ImageField(blank=True)
    name = models.CharField(max_length=72, default='User', unique=True)

    def save(self, *args, **kwargs):
        self.name = self.user.username
        super(Account, self).save(*args, **kwargs)


    def __str__(self):
        return self.name

base_app/currency/models.py
from django.db import models
from asgiref.sync import async_to_sync # for WebSocket
from channels.layers import get_channel_layer # for WebSocket

channels_layer = get_channel_layer()


class Currency(models.Model):
    ''' currency '''
    name = models.CharField(max_length=30)
    symbol = models.CharField(max_length=10)
    market_cap = models.BigIntegerField(default=0)
    price = models.DecimalField(
        default=0,
        max_digits=10,
        decimal_places=2,
        blank=True
     )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-price"]

    def save(self, *args, **kwargs):
        super(Currency, self).save(*args, **kwargs)
        # send update to socket
        try:
            #print(self)
            async_to_sync(channels_layer.group_send)(self.name, {
                'type': 'fetch_currency',
                'currency': self.name
            })
        except: pass

base_app/dashboard/models.py
from django.db import models
from currency.models import Currency
from account.models import Account


class Dashboard(models.Model):
    '''dashboard '''
    account = models.ForeignKey(Account, on_delete=models.PROTECT, null=True, blank=True)
    currency = models.ManyToManyField(Currency, blank=True)

base_app/account/views.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from dashboard.models import Dashboard
from .models import Account

def login_account(request):
    ''' login account '''

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('home:home'))

    return render(request, 'account/login.html', locals())


def logout_account(request):
    ''' logout account '''
    logout(request)
    return redirect(reverse('home:home'))

def dashboard(request):
    ''' dashboard account '''
    page = 'dashboard'
    if request.user.is_anonymous:
        pass
    else:
        try:
            account = Account.objects.get(user=request.user)
            dashboard = Dashboard.objects.get(account=account)
        except:
            redirect(reverse('account:login'))
    return render(request, 'account/dashboard.html', locals())

base_app/currency/views.py
from django.shortcuts import render
from .models import Currency
from .tasks import update_database


def currency_list(request):
    
    update_database.delay() # celery task: update db
    currencies = Currency.objects.all()
    page = 'currency'
    return render(request, 'currency/list.html', locals())

base_app/dashboard/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'dashboard/index.html')

def room(request, room_name):
    return render(request, 'dashboard/room.html', {
        'room_name': room_name
    })

base_app/home/views.py
from django.shortcuts import render


def home(request):
    page = 'home'
    return render(request, 'home/entrypoint.html', locals())

def landing(request):
    return render(request, 'home/landing.html')

base_app/currency/templates/currency/list.html
{% extends 'home/base.html' %}

{% block content %}
<section class="container currency">
  <h1 class="text-center">All Currencies</h1>
  <table class="table-3">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Symbol</th>
        <th>Market Cap</th>
        <th>Price</th>
        <th>Add to Dashboard</th>
      </tr>
    </thead>
    <tbody>
      {% for currency in currencies %}
      <tr>
        <td data-label="numb">{{ forloop.counter }}</td>
        <td data-label="name">{{ currency.name }}</td>
        <td data-label="symbol">{{ currency.symbol }}</td>
        <td data-label="market_cap">{{ currency.market_cap }}</td>
        <td data-label="price">{{ currency.price }}</td>
        <td data-label="add"><ion-icon name="add-outline"></ion-icon></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endblock %}

base_app/dashboard/templates/dashboard/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
     document.querySelector('#room-name-input').focus();
     document.querySelector('#room-name-input').onkeyup = function(e) {
       if (e.keyCode === 13) {  // enter, return
         document.querySelector('#room-name-submit').click();
       }
     };

     document.querySelector('#room-name-submit').onclick = function(e) {
       var roomName = document.querySelector('#room-name-input').value;
       window.location.pathname = '/dashboard/' + roomName + '/';
     };
    </script>
</body>
</html>

base_app/dashboard/templates/dashboard/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
  </head>
  <body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <textarea id="currency-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
     const roomName = JSON.parse(document.getElementById('room-name').textContent);

     const chatSocket = new WebSocket(
       'ws://'
       + window.location.host
       + '/ws/chat/'
       + roomName
       + '/'
     );

     chatSocket.onmessage = function(e) {
       const data = JSON.parse(e.data);
       document.querySelector('#chat-log').value += (data.message + '\n');
       document.querySelector('#currency-log').value += (data.currency + '\n');
     };
     
     chatSocket.onclose = function(e) {
       console.error('Chat socket closed unexpectedly');
     };

     document.querySelector('#chat-message-input').focus();
     document.querySelector('#chat-message-input').onkeyup = function(e) {
       if (e.keyCode === 13) {  // enter, return
         document.querySelector('#chat-message-submit').click();
       }
     };

     document.querySelector('#chat-message-submit').onclick = function(e) {
       const messageInputDom = document.querySelector('#chat-message-input');
       const message = messageInputDom.value;
       chatSocket.send(JSON.stringify({
         'message': message
       }));
       messageInputDom.value = '';
     };
    </script>
  </body>
</html>

base_app/home/templates/home/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    {% include 'snippets/get-bootstrap-css.html' %}
    {% include 'snippets/get-ioicons.html' %}
    <link href="{% static 'home/css/home.css' %}" rel="stylesheet"/>
    <title>CryptoCurrency</title>
  </head>
  <body>
    <!-- header -->
    {% include 'snippets/header.html' %}

    <section id="content">
      <!-- main content block -->
      {% block content %}{% endblock %}
    </section>

    <!-- footer -->
    {% include 'snippets/footer.html' %}
    
    {% include 'snippets/get-bootstrap-js.html' %}
  </body>
</html>

base_app/home/templates/home/entrypoint.html
{% extends 'home/base.html' %}

{% block content %}
<div class="container">

  <div class="row col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">  
    <h1 class="text-center">Cryptocurrency</h1>
    <p>Hey! This program will help you track changes in
      the cryptocurrency world.
    </p>

    <p>
      Cryptocurrency is a form of payment that can be exchanged online for goods and services. Many companies have issued their own currencies, often called tokens, and these can be traded specifically for the good or service that the company provides. Think of them as you would arcade tokens or casino chips. You’ll need to exchange real currency for the cryptocurrency to access the good or service.
      Cryptocurrencies work using a technology called blockchain. Blockchain is a decentralized technology spread across many computers that manages and records transactions. Part of the appeal of this technology is its security.
    </p>
    <a class="col-12 col-sm-6 col-md-4 col-lg-3 button btn btn-outline-warning" href="#">Sing Up</a>
  </div>
</div>

{% endblock %}

base_app/home/templates/snippets/footer.html
<footer>
    <div class="bg-dark py-4">
      <div class="container text-center">
        <p class="text-muted mb-0 py-2">© 2021 AndwerZweb All rights reserved.</p>
      </div>
    </div>
</footer>

base_app/home/templates/snippets/get-bootstrap-css.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

base_app/home/templates/snippets/get-bootstrap-js.html
<!-- Option 2: Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

base_app/home/templates/snippets/get-ioicons.html
<!-- icons -->
<script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>

base_app/home/templates/snippets/header.html
<header class="header">
  <div>
    <h3 class="logo"><a href="{% url 'home:home' %}">
      <ion-icon id="logo-page" class="logo" name="logo-bitcoin"></ion-icon>
      CryptoCurrency</a>
    </h3>
    <nav class="nav">
      <a class="nav-link {% if page == 'home' %}active{% endif %}"
         href="{% url 'home:home' %}">Home</a>
      <a class="nav-link {% if page == 'currency' %}active{% endif %}"
         href="{% url 'currency:list' %}">Currencies</a>
      <a class="nav-link  {% if page == 'dashboard' %}active{% endif %}"
         href="{% url 'account:dashboard' %}">Dashboard</a>
      <div>
        <a class="button btn btn-warning" href="{% url 'account:login' %}">Sing In</a>
      </div>
    </nav>
  </div>
</header>